### ISSUE TITLE
Forge 1.19.2 Crashes when you use Compressed together with Create and enough other mods are present.

### ISSUE THREAD

**Issue by laserman120** [Nibaru/Compressed#2]
[#4933 Mod Pack crashes when too many mods are present.](https://github.com/Creators-of-Create/Create/issues/4933)

Due to believing the issue was caused by Create i made an issue there. All details including several different crash logs as well as latest.log can be found there, as well as all my testing.

**Comment by edgarogh** [comment]
The interesting part is around [lines 69-82](https://mclo.gs/K8p9zAz#L69):

```
		Caused by: java.lang.NullPointerException: Registry entry not present: create:copper_shingles
		at java.util.Objects.requireNonNull(Objects.java:334) ~[?:?] {re:mixin}
		at com.tterrag.registrate.util.entry.RegistryEntry.get(RegistryEntry.java:105) ~[Registrate-MC1.19-1.1.5.jar%23367!/:?] {re:mixin,re:classloading}
		at com.simibubi.create.foundation.block.CopperBlockSet.lambda$new$6(CopperBlockSet.java:98) ~[create-1.19.2-0.5.1.b.jar%23275!/:0.5.1.b] {re:classloading}
		at com.simibubi.create.foundation.block.CopperRegistries.lambda$inject$0(CopperRegistries.java:55) ~[create-1.19.2-0.5.1.b.jar%23275!/:0.5.1.b] {re:classloading}
		at com.google.common.collect.HashBiMap.forEach(HashBiMap.java:572) ~[guava-31.0.1-jre.jar%23121!/:?] {}
		at com.simibubi.create.foundation.block.CopperRegistries.lambda$inject$1(CopperRegistries.java:54) ~[create-1.19.2-0.5.1.b.jar%23275!/:0.5.1.b] {re:classloading}
		at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.0.1-jre.jar%23121!/:?] {}
		at net.minecraft.world.level.block.WeatheringCopper.m_154904_(WeatheringCopper.java:52) ~[client-1.19.2-20220805.130853-srg.jar%23351!/:?] {re:mixin,re:classloading,pl:mixin:APP:quark.mixins.json:WeatheringCopperMixin,pl:mixin:A}
		at net.minecraft.world.level.block.WeatheringCopperFullBlock.m_6724_(WeatheringCopperFullBlock.java:24) ~[client-1.19.2-20220805.130853-srg.jar%23351!/:?] {re:classloading}
		at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60823_(BlockBehaviour.java:792) ~[client-1.19.2-20220805.130853-srg.jar%23351!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,re:computing_frames,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:kubejs-common.mixins.json:BlockStateBaseMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.block.AccessBlockStateBase,pl:mixin:A}
		at games.twinhead.compressed.registry.RegisterBlocks.getSettingsFromBlock(RegisterBlocks.java:108) ~[compressed-1.8.0+1.19.2.jar%23269!/:1.8.0+1.19.2] {re:classloading}
		at games.twinhead.compressed.registry.RegisterBlocks.getBlock(RegisterBlocks.java:83) ~[compressed-1.8.0+1.19.2.jar%23269!/:1.8.0+1.19.2] {re:classloading}
		at games.twinhead.compressed.registry.RegisterBlocks.lambda$registerBlocks$4(RegisterBlocks.java:35) ~[compressed-1.8.0+1.19.2.jar%23269!/:1.8.0+1.19.2] {re:classloading}
```

I don't know how `m_60823_` deobfuscates but it must correspond to one of these lines:
https://github.com/Nibaru/Compressed/blob/f3642c954cb830418caae27ef97cab861c97b4af/src/main/java/games/twinhead/compressed/registry/RegisterBlocks.java#L89-L96

It looks like Compressed is somehow triggering Create registration when it is registering its compressed blocks.

**Comment by LIPDProductionsInc** [comment]
Have the same issue on 1.18.2 with 1.8.0
